fix FlaskOAuth2ClientCredentialsAuth so that it supports the token kwarg (#126)
If the user passes token into the FlaskOAuth2ClientCredentialsAuth constructor, it needs serializer and session_key set before it runs the superclass constructor(s). Without this, the test fails with:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/requests_oauth2client/flask/auth.py", line 33, in __init__
    super().__init__(*args, **token_kwargs)
  File ".../requests_oauth2client/auth.py", line 69, in __init__
    self.__attrs_init__(client=client, token=token, leeway=leeway, token_kwargs=token_kwargs)
  File "<attrs generated init requests_oauth2client.auth.OAuth2AccessTokenAuth>", line 4, in __attrs_init__
  File ".../site-packages/attr/_make.py", line 1121, in __setattr__
    _OBJ_SETATTR(self, name, nval)
  File ".../requests_oauth2client/flask/auth.py", line 61, in token
    serialized_token = self.serializer.dumps(token)
                       ^^^^^^^^^^^^^^^
AttributeError: 'FlaskTokenAuth' object has no attribute 'serializer'
```